# Generated by Django 4.2.4 on 2023-08-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpf', models.CharField(max_length=150)),
                ('nome_empresa', models.CharField(max_length=200)),
                ('categoria_empresa', models.CharField(max_length=250)),
                ('quitado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizao', models.CharField(max_length=300)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
