# Generated by Django 4.2.4 on 2023-09-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='cnpf',
            new_name='cnpj',
        ),
        migrations.RenameField(
            model_name='stand',
            old_name='localizao',
            new_name='localizacao',
        ),
    ]
